
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-pvc
  namespace: my-ns
spec:
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi